name: Test

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'imgs\*'

jobs:
  test-no-install:
    runs-on: windows-latest
    name: No Install Needed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Install the Windows SDK 26100
        uses: ./
        with:
          version-sdk: 22621
          features: "OptionId.UWPCPP, OptionId.DesktopCPPx64, OptionId.DesktopCPPx86, OptionId.DesktopCPParm64, OptionId.DesktopCPParm"

  test-insider-install:
    runs-on: windows-latest
    name: Insider Install Needed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Install the Windows SDK 18995
        uses: ./
        with:
          version-sdk: 18995
          features: "OptionId.UWPCPP, OptionId.DesktopCPPx64"
  
  test-stable-install:
    runs-on: windows-latest
    name: Stable Install Needed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Install the Windows SDK 18362
        uses: ./
        with:
          version-sdk: 18362
          features: "OptionId.UWPCPP, OptionId.DesktopCPPx64"