name: Test

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'imgs\*'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Install the Windows SDK 22621 (already installed)
        uses: ./
        with:
          version-sdk: 22621
          features: "OptionId.UWPCPP, OptionId.DesktopCPPx64, OptionId.DesktopCPPx86, OptionId.DesktopCPParm64, OptionId.DesktopCPParm"

      - name: Install the Windows SDK 16299 (install needed)
        uses: ./
        with:
          version-sdk: 16299
          features: "OptionId.UWPCPP, OptionId.DesktopCPPx64"
